### ISSUE TITLE
Dev Question: How to make validate before controller save or create?

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/hawk#116]
Hi:
   Hawk is a tableless Rails App which not use ActiveRecorde,
   so we can not use ActiveRecorde callbacks such as "before_save" or "before_create",
   What should I do in Rails if I do want use such similar function?

   Regards,
   xin

**Comment by krig** [comment]
The question is: what is it you are trying to do? These callbacks do not make sense without a database..
