### ISSUE TITLE
Suggestion: unified Yes/No or true/false for boolean config options

### ISSUE THREAD

**Issue by liangxin1300** [ClusterLabs/hawk#126]
For example, in "Cluster Configuration" page, 
the value can be selected for "stonith-enabled" are "Yes/No",
but at right of the page, help messages said it's default value is "true";

It's a little bit strange although users can understand the difference.

Regards,
xin

**Comment by krig** [comment]
These are artifacts introduced in the theming / frontend of hawk, yeah.. We should have a unified standard everywhere. With the new hawk client, we will make sure to clean up these kinds of things.
