### ISSUE TITLE
Edit configuration not working with resources with dotted name

### ISSUE THREAD

**Issue by odino2018** [ClusterLabs/hawk#151]
While trying to edit resource with names like IP_1.1.1.1   
I am redirected to
https://..........:7630/404.html
"We can't find the page you're looking for" 
While it works for any other resource with a name without a dot it never works for resources with one or more dots in their name.

**Comment by ayoub-belarbi** [comment]
Hi @odino2018,
Thanks for reporting this, I will work on fixing this a soon as possible :)
