### ISSUE TITLE
remote connection environment variables not preserved

### ISSUE THREAD

**Issue by dmuhamedagic** [ClusterLabs/hawk#179]
cibadmin and some other utilities are run by hawk_invoke which clears the environment. Should it preserve CIB_host, CIB_user and others to be able to connect to a remote cluster node? The use case is to run hawk on a node which is not part of the cluster, for instance if the cluster runs on Debian where hawk is not readily available as a software package.
The remote connection is described here: [https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html-single/Pacemaker_Administration/#s-remote-connection](url)

**Comment by dmuhamedagic** [comment]
There's a pr #180 to preserve more environment variables.

**Comment by ayoub-belarbi** [comment]
Fixed by #180
