### ISSUE TITLE
Screenshots / Demo

### ISSUE THREAD

**Issue by sammcj** [ClusterLabs/hawk#26]
Hi, Any chance of some screenshots or a demo since it's a web product?

**Comment by tboerger** [comment]
Currently I'm working hard on a full rewrite of the UI. Afterwards I can create some screenshots and maybe a small screencast.

**Comment by ayoub-belarbi** [comment]
In case you still need it :) [New features in Hawk 2 - SLEHA 12 SP3 Beta](https://www.youtube.com/watch?v=MyenIdX8k4U)
