### ISSUE TITLE
Debian Support

### ISSUE THREAD

**Issue by sammcj** [ClusterLabs/hawk#27]
To your knowledge has anyone had hawk working on Debian - What could you see preventing this?

**Comment by tboerger** [comment]
If the dependencies can get resolved it should be no problem to run it on debian. I don't know if there are packages for pacemaker, crmsh and corosync available.

**Comment by krig** [comment]
madkiss has some relatively up-to-date packages for pacemaker 1.1.12 and crmsh 2.1.2, so there is no limitation there. I suspect there may be some incompatibilities with the hawk helper tools, but I don't know any portability bugs off-hand. So it may work as-is.

**Comment by krig** [comment]
Actually no, I can't find his updated packages so maybe he never finished them..

**Comment by krig** [comment]
Here they are: https://launchpad.net/~syseleven-platform/+archive/ubuntu/linux-ha

**Comment by sammcj** [comment]
Hmm. They're ubuntu packages, not Debian packages - ubuntu is quite different - it uses its own ubuntu-only init system etc...

**Comment by krig** [comment]
I think they might not use upstart, but I don't know for sure.

**Comment by tboerger** [comment]
Maybe somebody wants to fork the OBS packages to add the debian control files? Then it is quite easy to add debian support to hawk. An init file is already available in Hawk, we just need to add debian to the Makefile :)

**Comment by tboerger** [comment]
Why did you close the issue? :)

**Comment by sammcj** [comment]
Oh whoops I closed the wrong ticket! *facepalm*

**Comment by sammcj** [comment]
FYI - after months of working with Debian and HA I can honestly say it's not worth the trouble. Debian's pacemaker, corosync and other clustering pacakges are *very* old and contain a great deal of bugs that require various hacks / workarounds.

As much as we like Debian (we have 350 odd Debian servers) - it really isn't usable for clustering other than for the absolute basics. I've switched the clusters I've built to CentOS 7 and other than missing pacemaker support for legacy plugins - it is in a lot better shape.

**Comment by tboerger** [comment]
I would suggest SLES/openSUSE :)
Hawk is developed on openSUSE and SLES.

**Comment by Unksi** [comment]
There are actually some relatively new corosync/crmsh/pacemaker packages for Debian 8+ at [MMOD](http://ppa.mmogp.com/apt/debian/)

**Comment by tserong** [comment]
Just for the record, there's a Request for Package for Hawk on Debian at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=634344 (not that it's really seen much action...)

**Comment by ZleFox** [comment]
There are now updated pacemaker packages with current versions in Debian jessie-backports, so support for Debian is not so meaningless. I personally am using pacemaker clusters on several Debian servers and will be glad if the support for this distro is not left behind as it was during the jessie freeze. Thank you :)

**Comment by sammcj** [comment]
That sounds good!

So pacemaker, corosync, stonith packages, crmsh and ocf providers have all been update to or past what centos/rhel/suse have?

Any word if they work fine with the (presumably) provided selinux policies?

**Comment by ZleFox** [comment]
Currently these are the packaged versions:
pacemaker                     1.1.15-2~bpo8+1
corosync                      2.3.6-3~bpo8+1
crmsh                         2.2.0-1~bpo8+1
fence-agents                    4.0.22-2~bpo8+1
resource-agents                 1:3.9.7-1~bpo8+1
I managed to install the hawk with few tweaks and the default INIT policy and it seems to be working on a test single node - I will create a true cluster in the next week and will see if there are any issues.

**Comment by johnkeates** [comment]
Would you accept a PR adding Debian packaging?

**Comment by krig** [comment]
Yes, absolutely!

**Comment by johnkeates** [comment]
I have successfully built and tested hawk on Debian Stretch, with almost no modifications (except adding Gem sources). All other dependencies are in the standard Debian repositories so it seems the biggest challenge is the install script to get everything into place and figuring out Debian's Ruby Gem packaging policies. I'm thinking about checking with pcsd's package since it's also ruby and a stand-alone web interface provider. Since it's already in Debian, the packaging methods and installation setup should make for a good template for Hawk.

**Comment by krig** [comment]
That sounds really good, I'd really appreciate any patches that makes getting Hawk running on Debian an easier experience.

**Comment by ayoub-belarbi** [comment]
Will close this issue now,
thanks

**Comment by sm8ps** [comment]
HAWK looks extremely promising, especially for medium mediocre noobs like myself. I realize from other posts that manpower is short and unfortunately cannot offer much more than help with testing.
I am trying to reach out to @johnkeates for instructions on how to build and install on Debian/Ubuntu. Would you please share your experience here?
Greetings!

**Comment by krig** [comment]
@sm8ps Hi! There is now a more active HA community around Debian, so for the newer releases the packages are more up to date. It should in theory be possible to run Hawk in a SLE container on Debian if handling the dependencies is too difficult... At least the rest of the stack including crmsh is packaged and mostly up-to-date now, so building from source should be a possibility.

**Comment by sm8ps** [comment]
Thanks for your suggestion, @krig! I had really not thought about setting up a container for those purposes. This sounds like a very simple solution and I shall give it a try soon.
