### ISSUE TITLE
Dockerised Hawk?

### ISSUE THREAD

**Issue by sammcj** [ClusterLabs/hawk#39]
It would be great if Hawk had an official Dockerfile, this would mean anyone who wanted to use it could deploy it anywhere they could run Docker and it could contain just the bare minimum set of packages required to run the application.

Thoughts / comments / abuse all welcome :)

**Comment by tboerger** [comment]
I can try that. In general I would suggest openSUSE containers as an SUSE engineer, but the containers are damn large. So maybe AlpineLinux should be an option, the base images are really tiny, and the pacemaker version is quite new as you can see here: http://pkgs.alpinelinux.org/packages?package=%25pacemaker%25&repo=all&arch=x86_64

**Comment by krig** [comment]
Sounds great! I actually started looking at it a while ago, but to be maximally useful you'd like it to interact with a pacemaker cluster outside of the container. I don't think that's possible, though.

**Comment by tboerger** [comment]
@krig you can interact with anything outside of the container.

**Comment by krig** [comment]
@tboerger Oh! Well, in that case, I'm all for it :)

**Comment by tboerger** [comment]
And in worst case you can bind the container to the host network to use the multicast and UDP actions/connections used by corosync.

**Comment by sammcj** [comment]
This would be really neat, I'm so glad you're considering it.

I've just spent all day trying to build hawk for CentOS 7 with no success at all so this would be very helpful!

**Comment by sammcj** [comment]
Unfortunately I don't have *any* experience with SUSE so I just downloaded the latest 'tumbleweed' DVD ISO and selected to install hawk but it was riddled with dependency failures, then when hawk tried to start puma was erroring out on some gems etc...

If I had more time I'd write a Dockerfile for this but I don't have the time to figure out SUSE at the moment, If someone was able to write line by line what needs to be install from a bare SUSE 13.2 (or whatever?) install to get hawk + puma + nginx installed and working I could pretty quickly whip it up though?

**Comment by krig** [comment]
Yeah, unfortunately Rails 4.2 is broken in Tumbleweed at the moment (working on fixing it) :/ We have a Vagrantfile which sets up openSUSE 13.2 with hawk and a sample configuration in the repository. The chef cookbook which configures hawk might be helpful: https://github.com/ClusterLabs/hawk/tree/master/chef/cookbooks/hawk

It doesn't configure nginx though, it just runs hawk through puma directly. This is how we run hawk anyway, since it's not designed for heavy traffic and puma can handle SSL.

**Comment by krig** [comment]
I should note that the Vagrant configuration is a little bit special since Vagrant really wants the user on the VM to be `vagrant`, but normally hawk expects to run as the `hacluster` user.

**Comment by sammcj** [comment]
OK, I think I can do this if I can find time. WML

**Comment by tboerger** [comment]
Feel free to contribute it :)

**Comment by sammcj** [comment]
Will do if it actually works - I've actually already got it up and running in a docker container but it's the old version straight from 13.2 and I'm yet to sort mapping the external services etc...

https://github.com/sammcj/hawk/commit/89e6d55347a4700746c74927303b57a8ba5660f2

**Comment by krig** [comment]
An update here: I created a container of the current development version:

https://hub.docker.com/r/krig/hawk/

It gets pacemaker and Hawk up and running, but I wouldn't try to use it in production.

**Comment by tboerger** [comment]
Please unassign me :)

**Comment by krig** [comment]
@tboerger no problem :)

**Comment by ayoub-belarbi** [comment]
Since no new updates regarding this thread, will close it now.
Thanks
