### ISSUE TITLE
HAWK in a subdirectory

### ISSUE THREAD

**Issue by pndiku** [ClusterLabs/hawk#62]
I've tried all sorts of combinations of config.relative_url_root and ENV["ROOT_URL"] but hawk refuses to run in a subdirectory. 

Is this a puma issue or a hawk issue?

**Comment by krig** [comment]
Hmm, what do you mean with run in a subdirectory? You mean have hawk rooted at domain:port/something/hawk ?

That's something we haven't really considered, so I don't really know what might be the problem in making that work.

I'm guessing you have another web server with a virtual root which points to the puma instance?

**Comment by pndiku** [comment]
I need hawk accessible through a reverse proxy. 

Another way it would work is if hawk's internal URLs were not absolute, e.g. "assets", instead of "/assets".

**Comment by krig** [comment]
I think we're pretty good at using the rails facilities for building URLs, so if there is a way to get rails to generate relative URLs rather than absolute ones, that should hopefully do the trick.

**Comment by krig** [comment]
According to the documentation, `config.relative_url_root` should be all you need to modify. What was the problem that you had after changing it? Any kinds of logs or error messages you can attach here might help in figuring it out.

**Comment by tboerger** [comment]
Just removing the slash won't work, you need to set a base href. We are using the rails route helper everywhere, so it should be doable if rails gets configured properly

**Comment by tboerger** [comment]
Just for reverence http://edgeguides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root

**Comment by pndiku** [comment]
Like I wrote in the initial post, I tried `config.relative_url_root`. I don't get any errors, but there's no change. It's still only accessible at `https://[IP]:7630` instead of `https://[IP]:7630/hawk/`

**Comment by fibidifips** [comment]
currently i'm stuck at the same problem - i also need remote proxy functionality

**Comment by krig** [comment]
It should be possible to configure Puma to listen to a UNIX socket, and have the proxy server talk to that socket instead. Maybe something like that would work better.
You would need to modify the Puma configuration file, I suspect. I'll try to look at configuring this myself as soon as I have time.

**Comment by nonicknamewasleftforme** [comment]
Is there a solution to this issue or has the issue just been closed because of inactivity?

I'm trying to setup a reverse proxy with apache mod_proxy for accessing hawk through restrictive firewalls.

**Comment by krig** [comment]
This is still not possible as far as I know, Hawk needs a dedicated port and cannot serve from a subdirectory (so `<ip>:<port>` is possible, but `<ip>:<port>/hawk` is not).
